[package]
name = "energy-server"
version = "0.1.0"
authors = ["Kyle <abramowitzk@gmail.com>"]

[dependencies]
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"
log = "0.4.5"
iron = "0.6.0"
params = "0.8.0"
